carpool-location-svc
ABPAB/peer-to-peer-carpooling pull request #3
Opened 2024-11-14 14:15 UTC by Phenomenal1709

This PR provides a service for updating and managing users' real-time location data for a car-pooling application. It periodically updates the user's location in  Mongo-Atlas database.

2024-11-15 08:50 UTC, pawanpk87 requested changes
Please remove the credentials

2024-11-15 08:50 UTC, pawanpk87 commented on backend/carpool-location-svc/.env
Remove the credentials

2024-11-16 06:27 UTC, PragatiUpadhyay-Codebase approved these changes, later dismissed

2024-11-16 12:35 UTC, pawanpk87 approved these changes

2024-11-16 14:29 UTC, Phenomenal1709 commented
> Please remove the credentials

Removed!

2024-11-19 02:22 UTC, gopal0208 approved these changes

2024-11-19 02:22 UTC, merged